AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function deployment with Java 21 runtime

Parameters:
  LambdaHandler:
    Type: String
    Description: The handler for the Lambda function
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket containing the Lambda function JAR file
  S3Key:
    Type: String
    Description: The S3 key (file name) of the Lambda function JAR file

Resources:
  EugeniaLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Eugenia-lambda-function
      Handler: !Ref LambdaHandler
      Role: arn:aws:iam::087702913441:role/c145811a3776739l8957353t1w08770291344-LambdaSLRRole-mrwVZF3KbJFJ
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Runtime: java21
      Timeout: 10
      MemorySize: 512
